### ISSUE TITLE
[typescript-cached-transpile] Can this work with regular tsc?

### ISSUE THREAD

**Issue by CMCDragonkai** [cspotcode/personal-monorepo#7]
**Is your feature request related to a problem? Please describe.**

Does the cache help normal tsc compilation? Or is only useful for `ts-node`?

**Describe the solution you'd like**

I use `jest` to run tests written in TS. Was wondering if `jest` can benefit from a typescript cache.

**Comment by cspotcode** [comment]
This only works for `transpileModule` which skips typechecking.  `tsc` does not have a flag to skip typechecking.

For regular tsc, use `--incremental` for the fastest rebuilds.

For `ts-node`, use our swc integration: https://typestrong.org/ts-node/docs/transpilers
swc is so much faster that caching becomes unnecessary and, in my limited testing, was actually *slower* than letting swc recompile every time.

**Comment by CMCDragonkai** [comment]
It appears `ts-jest` doesn't support `--incremental` yet. So that would only help when doing the final tsc build. So I guess this is only for `ts-node`.

I tried using `swc` before, and I hit some compilation errors so dropped it.
